import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { BsFillGridFill } from "react-icons/bs";
import { TbListDetails } from "react-icons/tb";
import { IoIosArrowForward } from "react-icons/io";
import SearchItem from "../../components/SearchItem";

type Props = {};

const Search = (props: Props) => {
  const router = useRouter();
  const path = router.asPath.split("/")[2];
  if (!path) {
    router.push("/");
  }

  const title = `Buy ${path.replaceAll("%20", " ")} from Kcibecom.com`;
  const [openCategory, setOpenCategory] = React.useState("");

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="relative">
        <div className="search__container md:mt-20 mt-10 mx-5 md:mx-10 flex justify-between items-start gap-4">
          <div className="search__filter min-w-[230px] bg-white shadow rounded p-3 hidden md:flex md:flex-col">
            <div className="search__filter--header"></div>
            <div className="search__filter--body">
              <div className="search__filter--category">
                <h3
                  className="search__category--header font-bold py-2 flex items-center justify-between cursor-pointer"
                  onClick={() => setOpenCategory("open")}
                >
                  <span>Category</span>{" "}
                  <IoIosArrowForward className="text-gray-500 text-sm" />
                </h3>
                <ul
                  className={`search__categories pl-2 ${
                    openCategory === "open" || openCategory === "openSub"
                      ? "h-auto"
                      : "h-0"
                  } overflow-hidden transition duration-300`}
                >
                  <li className="search__category">
                    <h3 className="category__header font-semibold py-2 flex items-center justify-between cursor-pointer">
                      <span>Electronics</span>{" "}
                      <IoIosArrowForward className="text-gray-500 text-sm -rotate-90" />
                    </h3>
                    <ul className="search__subcategories pl-2">
                      <li className="search__subcategory py-1  cursor-pointer">
                        Electro subCat
                      </li>
                      <li className="search__subcategory py-1">
                        Electro subCat
                      </li>
                      <li className="search__subcategory py-1">
                        Electro subCat
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
              <div className="search__filter--price"></div>
              <div className="search__filter--brand"></div>
              <div className="search__filter--rating"></div>
              <div className="search__filter--size"></div>
              <div className="search__filter--color"></div>
              <div className="search__filter--discount"></div>
            </div>
          </div>
          <div className="search__products bg-white shadow rounded p-3 w-full">
            <div className="search__products--header flex items-center justify-between px-3 py-3">
              <h4 className="search__found">647362 Items Found</h4>
              <div className="search__header--action flex items-center">
                <div className="search__header--sort mr-5 cursor-pointer">
                  <select
                    name="sort"
                    id="sort"
                    className="search__sort--select cursor-pointer outline-none"
                  >
                    <option value="popularity">Popularity</option>
                    <option value="rating">Rating</option>
                    <option value="low">Price (Low to High)</option>
                    <option value="high">Price (High to Low)</option>
                    <option value="newest">Newest</option>
                  </select>
                </div>
                <div className="search__header--view flex items-center">
                  <div className="search__view--grid mr-3 cursor-pointer">
                    <BsFillGridFill />
                  </div>
                  <div className="search__view--list cursor-pointer">
                    <TbListDetails />
                  </div>
                </div>
              </div>
            </div>
            <hr />
            <div className="search__products--body py-3 flex flex-wrap gap-2 justify-start">
              <SearchItem />
              <SearchItem />
              <SearchItem />
              <SearchItem />
              <SearchItem />
              <SearchItem />
            </div>
          </div>
        </div>
        <div className="search__filter--btn absolute bottom-0 left-0 right-0">
          <button className="search__filter--btn--mobile md:hidden bg-white shadow p-3 text-center font-semibold">
            Filter
          </button>
        </div>
      </div>
    </>
  );
};

export default Search;
