import React, { useState, useEffect } from "react";
import Link from "next/link";
import Head from "next/head";
import { useRouter } from "next/router";
import { toast } from "react-toastify";

import useAuthStore from "../../store/useAuthStore";
import { forgotPassword } from "../../services/auth";
import { PulseLoader } from "react-spinners";

type Props = {};

const ForgotPage = (props: Props) => {
  const [isLoading, setIsLoading] = useState(false);
  const [emailData, setEmailData] = useState("");
  const isLoggedIn = useAuthStore((state) => state.isAuthenticated);
  const router = useRouter();
  const btnStyles =
    "forgot__btn w-full rounded flex items-center justify-center py-[0.6rem] shadow-md relative font-semibold text-white hover:scale-95 transition ease-in-out delay-150 duration-200";

  const onInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEmailData(event.target.value);
  };

  const onSubmit = async (
    event: React.MouseEvent<HTMLButtonElement, MouseEvent>
  ) => {
    event.preventDefault();

    if (!emailData) {
      toast.error("Please Enter your email address!");
      return;
    }
    setIsLoading(true);
    forgotPassword(event, emailData, setIsLoading);
  };

  useEffect(() => {
    if (isLoggedIn) {
      router.push("/");
    }
  }, [isLoggedIn]);
  return (
    <>
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col items-center justify-center">
        <div className="login__logo my-8">
          <Link href="/">
            <h3 className="font-bold text-3xl primary-color cursor-pointer">
              KCIB<span className="secondary-color">ECOM</span>
            </h3>
          </Link>
        </div>
        <div className="forgot__container bg-white p-4 shadow-md rounded-md w-full max-w-[400px]">
          <div className="forgot__header text-center mt-5">
            <h1 className="text-2xl font-bold mb-2">Forgot Password</h1>
            <p className="forgot__desc text-sm text-gray-400">
              Enter your email address and we'll send you a link to reset your
              password.
            </p>
          </div>
          <div className="forgot__content">
            <form action="#" className="forgot__form my-3" id="login-form">
              <div className="forgot__form-group form__input relative w-full h-[45px] my-4">
                <input
                  type="email"
                  className="forgot__input w-full h-full outline-none border-b-2 border-gray-200 px-1"
                  id="email"
                  required
                  name="email"
                  value={emailData}
                  onChange={onInputChange}
                />
                <div className="underline"></div>
                <label
                  htmlFor="email"
                  className="forgot__label email absolute bottom-[10px] left-0 text-base text-[#aaa] transition ease-in-out delay-150 duration-300"
                >
                  Email
                </label>
              </div>
              <div className="forgot__form-group form__input flex justify-center flex-col">
                {!isLoading && (
                  <button
                    type="submit"
                    className={`forgot__btn--email secondary-bg ${btnStyles}`}
                    onClick={onSubmit}
                  >
                    Send Link
                  </button>
                )}
                <PulseLoader
                  size={15}
                  className="mx-auto my-3"
                  color={"#192a56"}
                  loading={isLoading}
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default ForgotPage;
