import React, { useState } from "react";
import Link from "next/link";
import { FaFacebookSquare } from "react-icons/fa";
import { BsGoogle } from "react-icons/bs";
import { AiOutlineEye, AiOutlineEyeInvisible } from "react-icons/ai";
import Head from "next/head";

type Props = {};

const ForgotPage = (props: Props) => {
  const [showPassword, setShowPassword] = useState(false);
  const btnStyles =
    "forgot__btn w-full rounded flex items-center justify-center py-[0.6rem] shadow-md relative font-semibold text-white hover:scale-95 transition ease-in-out delay-150 duration-200";
  return (
    <>
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col items-center justify-center">
        <div className="login__logo my-8">
          <Link href="/">
            <h3 className="font-bold text-3xl primary-color cursor-pointer">
              KCIB<span className="secondary-color">ECOM</span>
            </h3>
          </Link>
        </div>
        <div className="forgot__container bg-white p-4 shadow-md rounded-md w-full max-w-[400px]">
          <div className="forgot__header text-center mt-5">
            <h1 className="text-2xl font-bold mb-2">Forgot Password</h1>
            <p className="forgot__desc text-sm text-gray-400">
              Enter your email address and we'll send you a link to reset your
              password.
            </p>
          </div>
          <div className="forgot__content">
            <form action="#" className="forgot__form my-3" id="login-form">
              <div className="forgot__form-group relative w-full h-[45px] my-4">
                <input
                  type="email"
                  className="forgot__input w-full h-full outline-none border-b-2 border-gray-200 px-1"
                  id="email"
                  required
                />
                <div className="underline"></div>
                <label
                  htmlFor="email"
                  className="forgot__label email absolute bottom-[10px] left-0 text-base text-[#aaa] transition ease-in-out delay-150 duration-300"
                >
                  Email
                </label>
              </div>
              <div className="forgot__form-group">
                <button
                  type="submit"
                  className={`forgot__btn--email secondary-bg ${btnStyles}`}
                >
                  Send Link
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default ForgotPage;
