import type { NextPage } from "next";
import Head from "next/head";
import { DesktopNav, MobileNav } from "../components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Kcibecom - No 1 ecommerce site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <DesktopNav />
        <MobileNav />
      </main>
    </div>
  );
};

export default Home;
